spring:
  banner:
    location: banner.txt
  cloud:
    openfeign:
      client:
        config:
          github:
            url: https://api.github.com/
            decoder: feign.json.JsonDecoder
            logger-level: headers

logging:
  level:
    root: WARN
    io.gitlab.radio_rogal.never_retry.GitHub: debug
    io.gitlab.radio_rogal.never_retry.GitHubService: info
    org.apache.hc.client5.http.headers: debug
